[build]
  functions = "netlify/functions"  # Specify the folder for Netlify functions

[[redirects]]
  from = "/api/*"  # Match requests to the /api path
  to = "/.netlify/functions/proxy"  # Forward them to the Netlify function
  status = 200
  force = true
